### ISSUE TITLE
Proposed json schema

### ISSUE THREAD

**Issue by alexsasharegan** [octref/vuetypes#1]
I have a couple thoughts on the json schema that differ from the initial proposal. I've drafted a revised schema as typescript since I find this a useful exercise for seeing how things might be implemented and weighing the ergonomics of the schema against the ergonomics of parsing it.

```ts
type BasicPropType =
  | "string"
  | "number"
  | "boolean"
  | "object"
  | "array"
  | "date"
  | "any" /* Just like typescript any. For untyped props. */
  | "Class" /* ?Some escape hatch for Custom constructor types? */;
type EnumPropType = "enum";

type EnumValueSet = string | number;

type AttributeDescriptor<T extends EnumValueSet = any> =
  | {
      description: string;
      type: BasicPropType | BasicPropType[];
      defaultValue?: any;
      required?: boolean;
    }
  | {
      description: string;
      type: EnumPropType;
      defaultValue?: any;
      required?: boolean;
      enumVariants: EnumVariant<T>[];
    };

// EnumVariant descriptions should not use object keys
// for values because that will conflict with any non-string type.
type EnumVariant<T extends EnumValueSet> =
  | T
  | {
      value: T;
      description: string;
    };

type ComponentDescriptor = {
  /**
   * The component description
   */
  description: string;
  /**
   * A list of component attribute descriptors.
   */
  attributes: { [attrName: string]: AttributeDescriptor };
};

interface Root {
  components: { [tagName: string]: ComponentDescriptor };
}
```

**Comment by alexsasharegan** [comment]
I think this is how the above changes would look:

```json
{
  "components": {
    "v-button": {
      "description": "A button",
      "attributes": {
        "width": {
          "description": "The width of the button",
          "type": "number",
          "required": true
        },
        "height": {
          "description": "The height of the button",
          "type": "number",
          "required": true
        },
        "corner-style": {
          "description": "The style of the button's corner",
          "type": "enum",
          "enumVariants": [
            { "value": "round", "description": "Round corners" },
            { "value": "sharp", "description": "Sharp corners" },
            "none"
          ],
          "required": false,
          "defaultValue": "round"
        }
      }
    }
  }
}
```

**Comment by octref** [comment]
What's the reasoning for `enumVariants` and dropping `value` from `valueType`? Originally, the naming are very explicit and clear:

- HTML attribute has attribute **values**
- `valueType`, `defaultValue` and `enumValues` make it easy to see the relationships between the attributes

With your proposal, the relationships between the attribute values are less clear.

**Comment by alexsasharegan** [comment]
`valueType` => `type` maps 1:1 with the way vue component props are authored. I think that's clearer, personally. I'm not sure it matters terribly either way though since this structure is intended for tooling.

I did write a comment explaining the change in `enumVariants` due to the limitation of using JSON keys, and thus only strings. Enums should be able to support strings, numbers, and true/false (even though it's silly to do so when a boolean achieves the same thing).

I think you came at this with the mentality of making the relationship analogous to the component in use in a template. I come at this thinking that a component author will be publishing their component for others to consume, so they are going to be the ones creating a component vuetypes file. Better to align things closely to the component they are publishing.

It should also be mentioned that I am pretty happy with the schema you originally laid out. For me personally, it's about 90-95% of my ideal. Not sure how much all will agree on the final 5-10%.

**Comment by octref** [comment]
@alexsasharegan Thanks for the detailed feedback! I just made an update: https://github.com/octref/vuetypes/commit/2369f73930fd8345903c30eb1b47739e76b0d3d6. Previously the `enumValues` was not what I intended...

Naming-wise, I think `type` works since in this context `type` unambiguously refer to the type of the attribute, and it's closer to the authoring experience. So I fixed that.

> I did write a comment explaining the change in enumVariants due to the limitation of using JSON keys, and thus only strings. Enums should be able to support strings, numbers, and true/false (even though it's silly to do so when a boolean achieves the same thing).

Thanks, I made an update so you still specify the type as `string`, not `enum`. I can do attribute auto-completion If the attribute does have an `enum` key.

```
        {
          "corner-style": {
            "description": "The style of the button's corner",
            "type": "string",
            "enum": [
              { "value": "round", "description": "Round corners" },
              { "value": "sharp", "description": "Sharp corners" }
            ],
            "required": false,
            "default": "round"
          }
```

I believe that addresses all your suggestions so I'm closing this issue. But let me know if you have more feedback, thanks!

**Comment by alexsasharegan** [comment]
That's awesome! Thank you!

There is only one thing you haven't addressed. 

I mentioned that the `attributes` property found at the schema path `Schema[component].attributes` does not seem necessary to be an array of objects. Instead, it could just be an object, the keys of which would be the attribute name and the value would be the attribute descriptor. I think that would keep authors from creating an attribute object with multiple keys (which has undefined behavior in this spec currently) as well as restricting attribute name collisions.

Think of this case in the current schema:

```json
{
  "components": {
    "v-button": {
      "description": "A button",
      "attributes": [
        {
          "width": {
            "description": "The width of the button",
            "type": "number",
            "required": true
          },
          "height": {
            "description": "The height of the button",
            "type": "number",
            "required": true
          },
          "width": {
            "description": "A duplicate key",
            "type": "string",
            "required": false,
            "default": "1em"
          }
        }
      ]
    }
  }
}

```

I think by removing the array, we make this shape less prone to these kind of mistakes. The shape is less nested, and undefined state become less possible.

**Comment by octref** [comment]
The array was mostly to preserve orders of the entries, as objects do not guarantee orders. I made 2 changes:

- `components` and `attributes` are now arrays
- Each `component` and `attribute` have a `name` now

```json
{
  "components": [
    {
      "name": "v-button",
      "description": "A button",
      "attributes": [
        {
          "name": "width",
          "description": "The width of the button",
          "type": "number",
          "required": true
        },
        {
          "name": "height",
          "description": "The height of the button",
          "type": "number",
          "required": true
        },
        {
          "name": "corner-style",
          "description": "The style of the button's corner",
          "type": "string",
          "enum": [
            { "value": "round", "description": "Round corners" },
            { "value": "sharp", "description": "Sharp corners" }
          ],
          "required": false,
          "default": "round"
        }
      ]
    }
  ]
}
```

**Comment by alexsasharegan** [comment]
Ah, that makes sense. Any generated documentation from this schema should preserve order. Smart :+1:

**Comment by octref** [comment]
Thanks again for taking a look and providing feedback!
