### ISSUE TITLE
I think read the installed vue component library is the better way than `@vuetypes/xxx`

### ISSUE THREAD

**Issue by Zenser** [octref/vuetypes#3]
Here is my idea:
1. every vue components library publish there `component-description.json` file in there root folder
   like `element-ui/component-description.json`
2. vetur travel the `package.json` get the dependencies value, then get from `node_moduels/element-ui/component-description.json`, then it can get all component description.

How do you think that?

**Comment by octref** [comment]
This is what Quasar is doing: https://github.com/quasarframework/quasar/blob/dev/package.json#L109-L111. We can do this if each framework authors is onboard.

**Comment by Zenser** [comment]
@octref  Thanks for your reply.
I get it, but it is also not support dynamic read dependencies.
I want vetur support dynamic read `component-description.json` or other protocol like `Quasar`.
So, I make a PR.
[https://github.com/vuejs/vetur/pull/941](https://github.com/vuejs/vetur/pull/941).
How do you think about? Looking forward to your reply.😁

**Comment by octref** [comment]
I would rather standardize this. How does your component-description look like? Can you do it the same way as Quasar?

**Comment by Zenser** [comment]
`component-description.json` is just a file which contains "tags" and "attributes".
Of course, i can do it like Quasar.

`component-description.json` like:
```json
{
  "tags": {},
  "attributes": {}
}
```

**Comment by Zenser** [comment]
Hey, I change `component-description.json` to `package.json` vetur key. Just parse like `quasar`.
@octref 
My PR: [https://github.com/vuejs/vetur/pull/941](https://github.com/vuejs/vetur/pull/941)

**Comment by octref** [comment]
I merged your PR. I think `tags` and `attributes` is fine for now. It's by no means a standard yet.
